name: Python Release Workflow

# This workflow is triggered on releases
on:
  release:
    types: [published]

jobs:
  build-snowflake-app:
    runs-on: ubuntu-latest  # You can change this to your preferred environment
    environment: build_prod
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: List files in the repository
      run: ls
    - name: List files in the repository
      run: pwd

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install snowflake-snowpark-python


    - name: Build Snowflake Native App
      env:
        PACKAGE_RELEASE_VERSION: ${{ github.ref }}
        SNOWFLAKE_PROD_BUILD_ACCOUNT:  ${{ secrets.SNOWFLAKE_PROD_BUILD_ACCOUNT}}
        SNOWFLAKE_PROD_BUILD_USERNAME:  ${{ secrets.SNOWFLAKE_PROD_BUILD_USERNAME }}
        SNOWFLAKE_PROD_BUILD_PASSWORD:  ${{ secrets.SNOWFLAKE_PROD_BUILD_PASSWORD }}
        SNOWFLAKE_PROD_BUILD_ROLE: ${{ secrets.SNOWFLAKE_PROD_BUILD_ROLE }}
        SNOWFLAKE_PROD_BUILD_WAREHOUSE:  ${{ secrets.SNOWFLAKE_PROD_BUILD_WAREHOUSE }}
      run: python ./snowflake_app_build/app_builder.py #snowflake_native_app/snowflake_app_build/app_builder.py
