name: Python Release Workflow

# This workflow is triggered on releases
on:
  release:
    types: [published]

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # You can change this to your preferred environment

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: List files in the repository
      run: ls

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: python ./snowflake_app_build/app_builder.py "${{ github.ref }}" #snowflake_native_app/snowflake_app_build/app_builder.py
